---
- name: Install strapi-api-host
  hosts: all
  become: true
  become_method: sudo
  gather_facts: false
  connection: local

  tasks:
    - name: Create nodejs group
      group:
        name: nodejs
        state: present

    - name: Create nodejs user
      user:
        name: nodejs
        groups: nodejs
        shell: /bin/bash
        append: yes
        state: present
        create_home: yes

    - name: Download https://deb.nodesource.com/setup_12.x
      get_url:
        url: https://deb.nodesource.com/setup_12.x
        dest: /tmp/setup_12.x
        mode: '0440'

    - name: Add nodejs12x apt sources
      shell: bash /tmp/setup_12.x

    - name: Install apt packages
      apt:
        pkg:
          - nodejs
          - acl
          - sqlite3
          - build-essential
          - zile
          - tmux
          - git
          - fail2ban
          - zip

    - ufw: rule=allow name=OpenSSH
    - ufw: rule=allow port=80 proto=tcp
    - ufw: rule=allow port=8080 proto=tcp
    - ufw: state=enabled

    - name: Create /opt/strapi
      file:
        path: /opt/strapi
        state: directory
        mode: '0755'

    - name: Unarchive strapi build
      unarchive:
        src: /tmp/strapi-api-host-build.tar.gz
        dest: /opt/strapi
        remote_src: yes

    - name: Recursively change ownership /opt/strapi
      file:
        path: /opt/strapi
        state: directory
        recurse: yes
        owner: nodejs
        group: nodejs

    - name: Install node_modules
      become: true
      become_user: nodejs
      shell: rm -rf /opt/strapi/node_modules && npm i
      args:
        chdir: /opt/strapi

    - name: Copy .env file
      copy:
        src: /opt/strapi/.env.example
        dest: /opt/strapi/.env
        force: yes

    - name: Install pm2
      npm:
        name: pm2
        global: yes
        version: 4.4.1

    - name: Install pm2 system startup
      shell: pm2 startup -u nodejs --hp /home/nodejs

    - name: Startup strapi on startup
      shell: pm2 start ecosystem.config.js
      become: true
      become_user: nodejs
      args:
        chdir: /opt/strapi
